# Generated by Django 2.2.5 on 2019-12-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customer_username'),
        ('products', '0003_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=122)),
                ('shipping_total', models.DecimalField(blank=True, decimal_places=2, default=6.0, max_digits=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('products', models.ManyToManyField(null=True, to='products.Product')),
            ],
        ),
    ]
