# Generated by Django 2.2.5 on 2019-12-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
    ]
