# Generated by Django 2.2.5 on 2019-11-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
